// tasks
export const ADMIN_TASK_FETCH_REQUEST = "ADMIN_TASK_FETCH_REQUEST";
export const ADMIN_TASK_FETCH_SUCCESS = "ADMIN_TASK_FETCH_SUCCESS";
export const ADMIN_TASK_FETCH_FAIL = "ADMIN_TASK_FETCH_FAIL";

export const ADMIN_TASK_UPDATE_REQUEST = "ADMIN_TASK_UPDATE_REQUEST";
export const ADMIN_TASK_UPDATE_SUCCESS = "ADMIN_TASK_UPDATE_SUCCESS";
export const ADMIN_TASK_UPDATE_FAIL = "ADMIN_TASK_UPDATE_FAIL";

export const ADMIN_TASK_REMOVE_REQUEST = "ADMIN_TASK_REMOVE_REQUEST";
export const ADMIN_TASK_REMOVE_SUCCESS = "ADMIN_TASK_REMOVE_SUCCESS";
export const ADMIN_TASK_REMOVE_FAIL = "ADMIN_TASK_REMOVE_FAIL";

// questions
export const ADMIN_QUESTION_FETCH_REQUEST = "ADMIN_QUESTION_FETCH_REQUEST";
export const ADMIN_QUESTION_FETCH_SUCCESS = "ADMIN_QUESTION_FETCH_SUCCESS";
export const ADMIN_QUESTION_FETCH_FAIL = "ADMIN_QUESTION_FETCH_FAIL";
