// tasks
export const ADMIN_TASK_FETCH_REQUEST = "ADMIN_TASK_FETCH_REQUEST";
export const ADMIN_TASK_FETCH_SUCCESS = "ADMIN_TASK_FETCH_SUCCESS";
export const ADMIN_TASK_FETCH_FAIL = "ADMIN_TASK_FETCH_FAIL";

export const ADMIN_TASK_UPDATE_REQUEST = "ADMIN_TASK_UPDATE_REQUEST";
export const ADMIN_TASK_UPDATE_SUCCESS = "ADMIN_TASK_UPDATE_SUCCESS";
export const ADMIN_TASK_UPDATE_FAIL = "ADMIN_TASK_UPDATE_FAIL";

export const ADMIN_TASK_REMOVE_REQUEST = "ADMIN_TASK_REMOVE_REQUEST";
export const ADMIN_TASK_REMOVE_SUCCESS = "ADMIN_TASK_REMOVE_SUCCESS";
export const ADMIN_TASK_REMOVE_FAIL = "ADMIN_TASK_REMOVE_FAIL";

// questions
export const ADMIN_QUESTION_FETCH_REQUEST = "ADMIN_QUESTION_FETCH_REQUEST";
export const ADMIN_QUESTION_FETCH_SUCCESS = "ADMIN_QUESTION_FETCH_SUCCESS";
export const ADMIN_QUESTION_FETCH_FAIL = "ADMIN_QUESTION_FETCH_FAIL";

export const ADMIN_QUESTION_DATE_SAVE = "ADMIN_QUESTION_DATE_SAVE";

export const ADMIN_ANSWER_FETCH_REQUEST = "ADMIN_ANSWER_FETCH_REQUEST";
export const ADMIN_ANSWER_FETCH_SUCCESS = "ADMIN_ANSWER_FETCH_SUCCESS";
export const ADMIN_ANSWER_FETCH_FAIL = "ADMIN_ANSWER_FETCH_FAIL";

export const ADMIN_ANSWER_CREATE_REQUEST = "ADMIN_ANSWER_CREATE_REQUEST";
export const ADMIN_ANSWER_CREATE_SUCCESS = "ADMIN_ANSWER_CREATE_SUCCESS";
export const ADMIN_ANSWER_CREATE_FAIL = "ADMIN_ANSWER_CREATE_FAIL";

export const ADMIN_QA_FETCH_POST_REQUEST = "ADMIN_QA_FETCH_POST_REQUEST";
export const ADMIN_QA_FETCH_POST_SUCCESS = "ADMIN_QA_FETCH_POST_SUCCESS";

// notice
export const ADMIN_NOTICE_CREATE_REQUEST = "ADMIN_NOTICE_CREATE_REQUEST";
export const ADMIN_NOTICE_CREATE_SUCCESS = "ADMIN_NOTICE_CREATE_SUCCESS";
export const ADMIN_NOTICE_CREATE_FAIL = "ADMIN_NOTICE_CREATE_FAIL";

export const ADMIN_NOTICE_FETCH_REQUEST = "ADMIN_NOTICE_FETCH_REQUEST";
export const ADMIN_NOTICE_FETCH_SUCCESS = "ADMIN_NOTICE_FETCH_SUCCESS";
export const ADMIN_NOTICE_FETCH_FAIL = "ADMIN_NOTICE_FETCH_FAIL";

export const ADMIN_NOTICE_REMOVE_REQUEST = "ADMIN_NOTICE_REMOVE_REQUEST";
export const ADMIN_NOTICE_REMOVE_SUCCESS = "ADMIN_NOTICE_REMOVE_SUCCESS";
export const ADMIN_NOTICE_REMOVE_FAIL = "ADMIN_NOTICE_REMOVE_FAIL";
