// fetch
export const ADMIN_TASK_FETCH_REQUEST = "ADMIN_TASK_FETCH_REQUEST";
export const ADMIN_TASK_FETCH_SUCCESS = "ADMIN_TASK_FETCH_SUCCESS";
export const ADMIN_TASK_FETCH_FAIL = "ADMIN_TASK_FETCH_FAIL";

// remove
export const ADMIN_TASK_REMOVE_REQUEST = "ADMIN_TASK_REMOVE_REQUEST";
export const ADMIN_TASK_REMOVE_SUCCESS = "ADMIN_TASK_REMOVE_SUCCESS";
export const ADMIN_TASK_REMOVE_FAIL = "ADMIN_TASK_REMOVE_FAIL";
