// notices
export const DESK_NOTICE_FETCH_REQUEST = "DESK_NOTICE_FETCH_REQUEST";
export const DESK_NOTICE_FETCH_SUCCESS = "DESK_NOTICE_FETCH_SUCCESS";
export const DESK_NOTICE_FETCH_FAIL = "DESK_NOTICE_FETCH_FAIL";

// faqs
export const DESK_FAQ_FETCH_REQUEST = "DESK_FAQ_FETCH_REQUEST";
export const DESK_FAQ_FETCH_SUCCESS = "DESK_FAQ_FETCH_SUCCESS";
export const DESK_FAQ_FETCH_FAIL = "DESK_FAQ_FETCH_FAIL";

// qas
export const DESK_QA_FETCH_REQUEST = "DESK_QA_FETCH_REQUEST";
export const DESK_QA_FETCH_SUCCESS = "DESK_QA_FETCH_SUCCESS";
export const DESK_QA_FETCH_FAIL = "DESK_QA_FETCH_FAIL";

export const DESK_QA_CREATE_REQUEST = "DESK_QA_CREATE_REQUEST";
export const DESK_QA_CREATE_SUCCESS = "DESK_QA_CREATE_SUCCESS";
export const DESK_QA_CREATE_FAIL = "DESK_QA_CREATE_FAIL";

export const DESK_QA_CREATE_COMMENT_REQUEST = "DESK_QA_CREATE_COMMENT_REQUEST";
export const DESK_QA_CREATE_COMMENT_SUCCESS = "DESK_QA_CREATE_COMMENT_SUCCESS";
export const DESK_QA_CREATE_COMMENT_FAIL = "DESK_QA_CREATE_COMMENT_FAIL";

export const DESK_QA_FETCH_COMMENT_REQUEST = "DESK_QA_FETCH_COMMENT_REQUEST";
export const DESK_QA_FETCH_COMMENT_SUCCESS = "DESK_QA_FETCH_COMMENT_SUCCESS";
export const DESK_QA_FETCH_COMMENT_FAIL = "DESK_QA_FETCH_COMMENT_FAIL";

export const DESK_QA_FETCH_POST_REQUEST = "DESK_QA_FETCH_POST_REQUEST";
export const DESK_QA_FETCH_POST_SUCCESS = "DESK_QA_FETCH_POST_SUCCESS";