// notices
export const DESK_NOTICE_FETCH_REQUEST = "DESK_NOTICE_FETCH_REQUEST";
export const DESK_NOTICE_FETCH_SUCCESS = "DESK_NOTICE_FETCH_SUCCESS";
export const DESK_NOTICE_FETCH_FAIL = "DESK_NOTICE_FETCH_FAIL";

// faqs
export const DESK_FAQ_FETCH_REQUEST = "DESK_FAQ_FETCH_REQUEST";
export const DESK_FAQ_FETCH_SUCCESS = "DESK_FAQ_FETCH_SUCCESS";
export const DESK_FAQ_FETCH_FAIL = "DESK_FAQ_FETCH_FAIL";
