// qrcode
export const QRCODE_FETCH_REQUEST = "QRCODE_FETCH_REQUEST";
export const QRCODE_FETCH_SUCCESS = "QRCODE_FETCH_SUCCESS";
export const QRCODE_FETCH_FAIL = "QRCODE_FETCH_FAIL";

// address input
export const ADDRESS_INPUT_REQUEST = "ADDRESS_INPUT_REQUEST";
export const ADDRESS_INPUT_SUCCESS = "ADDRESS_INPUT_SUCCESS";
export const ADDRESS_INPUT_FAIL = "ADDRESS_INPUT_FAIL";
