// post
export const WRITTEN_POST_FETCH_REQUEST = "WRITTEN_POST_FETCH_REQUEST";
export const WRITTEN_POST_FETCH_SUCCESS = "WRITTEN_POST_FETCH_SUCCESS";
export const WRITTEN_POST_FETCH_FAIL = "WRITTEN_POST_FETCH_FAIL";

export const SEND_POST_FETCH_REQUEST = "SEND_POST_FETCH_REQUEST";
export const SEND_POST_FETCH_SUCCESS = "SEND_POST_FETCH_SUCCESS";
export const SEND_POST_FETCH_FAIL = "SEND_POST_FETCH_FAIL";
export const SEND_QA_POST_FETCH_SUCCESS = "SEND_QA_POST_FETCH_SUCCESS";

export const RECEIVE_POST_FETCH_REQUEST = "RECEIVE_POST_FETCH_REQUEST";
export const RECEIVE_POST_FETCH_SUCCESS = "RECEIVE_POST_FETCH_SUCCESS";
export const RECEIVE_POST_FETCH_FAIL = "RECEIVE_POST_FETCH_FAIL";
export const RECEIVE_QA_POST_FETCH_SUCCESS = "RECEIVE_QA_POST_FETCH_SUCCESS";
