// register
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_AUTH_LOGIN_REQUEST = "USER_AUTH_LOGIN_REQUEST";
export const USER_AUTH_LOGIN_SUCCESS = "USER_AUTH_LOGIN_SUCCESS";
export const USER_AUTH_LOGIN_FAIL = "USER_AUTH_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_TOKEN_CHECK_SUCCESS = "USER_TOKEN_CHECK_SUCCESS";
export const USER_TOKEN_CHECK_REQUEST = "USER_TOKEN_CHECK_REQUEST";

// sms
export const USER_PHONE_SMS_REQUEST = "USER_PHONE_SMS_REQUEST";
export const USER_PHONE_SMS_SUCCESS = "USER_PHONE_SMS_SUCCESS";
export const USER_PHONE_SMS_FAIL = "USER_PHONE_SMS_FAIL";
export const USER_PHONE_SMS_CHECK_REQUEST = "USER_PHONE_SMS_CHECK_REQUEST";
export const USER_PHONE_SMS_CHECK_SUCCESS = "USER_PHONE_SMS_CHECK_SUCCESS";
export const USER_PHONE_SMS_CHECK_FAIL = "USER_PHONE_SMS_CHECK_FAIL";

// update password
export const USER_FIND_PASS_SMS_REQUEST = "USER_FIND_PASS_SMS_REQUEST";
export const USER_FIND_PASS_SMS_SUCCESS = "USER_FIND_PASS_SMS_SUCCESS";
export const USER_FIND_PASS_SMS_FAIL = "USER_FIND_PASS_SMS_FAIL";

export const USER_UPDATE_PASS_REQUEST = "USER_UPDATE_PASS_REQUEST";
export const USER_UPDATE_PASS_SUCCESS = "USER_UPDATE_PASS_SUCCESS";
export const USER_UPDATE_PASS_FAIL = "USER_UPDATE_PASS_FAIL";
